# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install JupyterLab
      run: pip install jupyterlab papermill numpy matplotlib
    - name: Generate markdown
      run: cat test.ipynb | papermill -p foo "bar" | jupyter nbconvert --stdin --TemplateExporter.exclude_input=True --to html --output test.html && mkdir -p public && mv *.html public/
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./public

